/* WFI Prompt Book — all 280 prompts, loaded by index.html */
const PROMPT_SECTIONS = [
  {
    id:"diagnostic", title:"Diagnostic Skills", color:"#00d4ff",
    files:[
      { id:"data-audit", title:"Workforce Data Audit", prompts:[
        "Map every data field currently collected in our HRIS and flag any field with more than 10% missing values. For each gap, identify which workforce planning models depend on that field.",
        "Review our job architecture data: flag duplicate job codes, titles with no mapped competencies, and roles where the salary grade has not been updated in more than three years.",
        "Assess our attrition tracking methodology. Do we distinguish voluntary vs involuntary exits? Regrettable vs non-regrettable? If not, draft a taxonomy and the system changes needed to support it.",
        "Audit the freshness of our headcount data: how often is it updated, who owns it, and where do the numbers diverge between HR, Finance, and business unit reports?",
        "Identify the top five data quality issues limiting our ability to run a reliable workforce demand forecast. Estimate the effort to fix each and the risk of proceeding without fixing it.",
        "Map our current workforce data assets against a people analytics maturity model. Where are we at Level 1 (descriptive), Level 2 (diagnostic), or Level 3 (predictive)?",
        "List every external labour market data source we use. Evaluate each for coverage, update frequency, and cost-to-value ratio.",
        "Review our performance data for rating distribution: are we experiencing compression? How does this affect our ability to use performance in talent decisions?",
        "Identify all places where the same workforce metric is defined differently across HR, Finance, and the business. Draft a data dictionary entry for headcount that all three functions can agree on.",
        "Audit our diversity data: which demographic fields are collected, what are the opt-out rates, and which analyses are blocked by data gaps?",
        "Assess whether our current HR data infrastructure can support a skills ontology. What are the key technical and governance requirements?",
        "Map the lineage of our standard headcount report from raw source through transformation to final metric. Identify every step where human intervention creates error risk.",
        "Identify our riskiest single point of data dependency — the one dataset whose loss would most severely limit our workforce planning capability.",
        "Evaluate the gap between the workforce data we collect and the data needed to answer the CHRO's top three board-level people questions. Prioritise the gaps by strategic impact.",
        "Review our internal mobility data: do we track lateral moves, project assignments, and stretch roles? What is missing to give us a better picture of talent flow?",
        "Compare our actual data governance practices to what is documented in our HR data policy. List the top five deviations and the risk each creates.",
        "Estimate the cost of our current workforce data quality problems in analyst hours, bad decisions, and delayed projects. Build a business case for a data quality initiative.",
        "Identify which of our workforce KPIs are lagging vs leading indicators. What leading indicators are we not tracking that would improve our ability to anticipate problems?"
      ]},
      { id:"ai-readiness", title:"AI Readiness", prompts:[
        "Assess our organisation's AI readiness across five dimensions: data infrastructure, talent capability, governance, leadership alignment, and change appetite. Rate each 1–5 and identify the two lowest-scoring dimensions.",
        "Write 10 interview questions to run with HR leaders to assess how comfortable they are with AI-assisted decision-making in talent processes.",
        "Identify the top three workforce processes where AI could add immediate value with the lowest implementation risk. Explain the selection criteria.",
        "Map our current HR technology stack and identify which tools already have embedded AI features we are not using. Estimate the value being left on the table.",
        "Draft a one-page AI literacy assessment for HR business partners covering model interpretation, bias recognition, and ethical guardrails.",
        "Identify the three biggest AI-related risks in our workforce intelligence function — data privacy, algorithmic bias, explainability gaps. Assess current exposure and mitigation for each.",
        "Evaluate our data governance framework against the requirements for responsible AI use in people decisions. List the gaps and prioritise by risk level.",
        "Assess leadership readiness: what signals from the C-suite indicate support for AI in HR? What signals indicate resistance? How do we close the gap?",
        "Identify legal and regulatory constraints on AI use in employment decisions in our operating jurisdictions. Summarise the no-go zones and the grey areas.",
        "Draft a vendor assessment rubric for AI-powered HR tools: explainability, bias testing, data security, compliance certifications, and model refresh cadence.",
        "Map current decision rights for people analytics outputs: who can see model results, who can act on them, who is accountable for outcomes?",
        "Evaluate the skills gap in our people analytics team against requirements for building and deploying AI models. What roles do we need that we do not currently have?",
        "Create a readiness scorecard for piloting AI-assisted workforce planning: data readiness (0–25), process readiness (0–25), talent readiness (0–25), governance readiness (0–25).",
        "Identify our most data-rich HR process — the one with the most complete, clean, longitudinal data — and assess whether it is the right place to start an AI pilot.",
        "Draft the questions our CHRO will get asked by the board about AI in HR, and write model answers for each.",
        "Map AI adoption barriers by stakeholder group: HR leaders, HRBPs, business unit leaders, employees. What is the primary concern for each group?",
        "Evaluate three AI deployment models — build in-house, configure vendor platform, partner with consulting firm — against our organisational constraints and risk appetite.",
        "Write a 90-day AI readiness sprint plan: assessments, pilots, governance decisions, and stakeholder engagements before committing to a full AI roadmap."
      ]},
      { id:"use-case-priority", title:"Use Case Prioritisation", prompts:[
        "List the top 10 use cases for AI in our workforce planning function. Score each on strategic value, data readiness, implementation complexity, and stakeholder appetite.",
        "Apply a 2×2 matrix — impact vs feasibility — to our potential AI use cases. Identify the quick wins quadrant and the big bets quadrant.",
        "Write a one-paragraph business case for each of our top three AI use cases: the problem, expected outcome, investment required, and risk profile.",
        "Identify AI use cases that could be funded through cost savings vs those requiring net-new investment. Which set is easier to move through budget approval?",
        "Map each proposed AI use case to a specific CHRO or CEO priority. Eliminate or defer any use case that cannot be tied to a strategic objective.",
        "Assess the organisational cost of not automating our top three manual workforce processes. Use this as the do-nothing baseline in our prioritisation model.",
        "For our highest-priority AI use case, write the user story: as a [role], I want [AI capability] so that I can [outcome]. Include the acceptance criteria.",
        "Identify which AI use cases require changes to decision rights or governance before they can be deployed. Separate can-start-now cases from needs-governance-change cases.",
        "Map our AI use case roadmap over 18 months: what do we pilot in months 1–3, scale in months 4–9, and institutionalise in months 10–18?",
        "Evaluate whether our AI use case list is too operationally focused. Are we missing any strategic uses of AI in workforce planning that could differentiate us?",
        "Identify the AI use case that would have the highest impact on manager experience.",
        "Assess each AI use case for employee trust risk: which could damage trust if misunderstood or misapplied? How do we sequence communications around them?",
        "Write the scoring rubric we will use to evaluate proposals for AI investment from HR business partners. What are the five criteria and their relative weights?",
        "Identify AI use cases that overlap with initiatives already underway in IT, Finance, or the business. Where can we piggyback rather than build separately?",
        "Stress-test our top AI use case: what are the three most likely failure modes? For each, assess probability and impact, and write a mitigation plan.",
        "Estimate the total addressable value of AI across our workforce planning function over three years using conservative, base, and optimistic scenarios.",
        "Draft the criteria for deciding when to pause or kill an AI pilot that is not delivering expected results.",
        "Write a one-page executive summary of our AI use case roadmap for the CHRO: what we are doing, why, in what order, and what we need to succeed."
      ]},
      { id:"build-buy", title:"Build vs Buy", prompts:[
        "For our top AI use case, evaluate three options: build in-house, configure an existing vendor platform, and purchase a point solution. Compare on total cost of ownership, time to value, and flexibility.",
        "Write the vendor RFP criteria for a workforce planning platform: must-haves, nice-to-haves, and disqualifiers.",
        "Assess our internal capability to build and maintain a workforce forecasting model. What skills, infrastructure, and time are required? What is the realistic total cost?",
        "Identify which of our workforce intelligence capabilities should be treated as core differentiators to build vs commodity functions to buy.",
        "Evaluate our current HR tech vendors for AI capabilities they are rolling out that we have not yet activated. What is the low-effort, high-value activation list?",
        "Write a risk register for a build-in-house workforce analytics platform covering technology risk, talent risk, timeline risk, and adoption risk.",
        "Draft the contract terms we should insist on with any AI vendor handling employee data: data residency, model explainability, audit rights, and termination provisions.",
        "Map the hidden costs of a buy decision: implementation, customisation, integration, training, and ongoing licensing. Compare to the visible price tag.",
        "Identify which workforce intelligence capabilities we currently rely on consultants for that we should bring in-house. What is the build plan?",
        "Assess the opportunity cost of build: if our people analytics team builds a custom tool, what vendor relationships and strategic projects get deprioritised?",
        "Write the criteria for evaluating a partnership model — with a labour market data provider or AI research firm — vs build or buy.",
        "Identify the single workforce intelligence capability that is most critical to own ourselves. What would we lose by outsourcing it?",
        "Draft a three-year technology roadmap for our workforce intelligence function assuming a buy-and-integrate strategy. What platforms, in what sequence?",
        "Evaluate the market for workforce planning platforms: who are the top five vendors, what are their differentiating capabilities, and what are their known weaknesses?",
        "Write the business case for consolidating three separate HR analytics tools onto one platform. Quantify the integration overhead we are currently paying.",
        "Assess our vendor dependency risk: which of our current workforce intelligence capabilities would be severely disrupted if our primary vendor were acquired or shut down?"
      ]}
    ]
  },
  {
    id:"planning", title:"Workforce Planning", color:"#8b5cf6",
    files:[
      { id:"demand", title:"Demand Forecasting", prompts:[
        "Build a structured intake template for collecting workforce demand drivers from business unit leaders. Include revenue targets, productivity assumptions, new capability needs, and planned exits.",
        "Convert our three-year strategic plan into a headcount demand model. For each business initiative, identify the role families impacted, the net headcount change, and the timeline.",
        "Write the questions I should ask the CFO to understand which financial assumptions drive their headcount model. How do I reconcile HR's view with Finance's?",
        "Identify the top five external drivers that should inform our workforce demand forecast: economic, competitive, regulatory, technological, and demographic.",
        "Draft a demand forecast methodology one-pager for business unit leaders: what inputs we need from them, how we will use the data, and what they will get back.",
        "Build a productivity assumption template: for each major role family, document the current output-per-FTE baseline and expected change over the planning horizon.",
        "Identify the workforce demand signals most likely to be wrong in our current forecast. What assumptions are we most uncertain about, and how do we bound the uncertainty?",
        "Write the logic for converting a revenue growth assumption into a headcount number for a specific function. What is the ratio, and what breaks it?",
        "Map the demand forecast to cost: for each role family in the plan, calculate the fully-loaded cost per FTE and total forecasted labour cost in each scenario.",
        "Identify which business units are most likely to understate their demand (optimistic about efficiency) and which to overstate it (padding). Write calibration questions for each.",
        "Build a demand sensitivity analysis: how does our headcount forecast change if revenue grows 10% faster or slower than plan? Which roles are most elastic?",
        "Identify the workforce demand implications of our top three technology investments — automation, ERP upgrade, AI deployment. How do these change role mix and headcount?",
        "Draft a demand forecast review cadence: when do we update, who attends, and what triggers an off-cycle revision?",
        "Write the CHRO's demand forecast narrative for the board: what are we planning to hire, why, and what are the key risks?",
        "Identify roles where demand is growing faster than our ability to source or develop talent internally. These are our critical supply-risk roles.",
        "Build a workforce demand waterfall: starting from current headcount, model growth hires, backfill hires, and attrition to arrive at total hiring volume by quarter.",
        "Write the definition of headcount we will use in our demand forecast and get every stakeholder aligned before modelling.",
        "Identify the workforce demand implications of our acquisition pipeline. What integration planning is required for each scenario?"
      ]},
      { id:"supply", title:"Supply Modelling", prompts:[
        "Build a talent supply model for our top ten critical role families. Project internal supply at end of each planning year using historical attrition and promotion rates.",
        "Identify the attrition drivers in our highest-priority role families. Use exit survey data, tenure distributions, and compensation benchmarks to diagnose root causes.",
        "Write a methodology for segmenting attrition into planned vs unplanned and regrettable vs non-regrettable. How do we use each segment differently in our supply model?",
        "Model our internal mobility rate: what percentage of open roles are filled internally vs externally? How does this compare to our strategic intent?",
        "Build a pipeline health assessment for our top five critical roles: how many qualified internal candidates are in a 0–12 month, 12–24 month, and 24–36 month readiness window?",
        "Identify the supply bottlenecks in our talent pipeline: which roles have the thinnest bench, and what is the consequence if those positions turn over?",
        "Write the logic for a retirement risk model: using age, tenure, and benefits vesting data, estimate which employees are likely to retire in each planning year.",
        "Build a promotion velocity model: how long does it take for talent to move from one level to the next? How does this compare to employee expectations?",
        "Identify the supply implications of our current L&D investments. Which programmes are producing ready-now talent for critical roles, and which have low ROI?",
        "Model the impact of a 20% increase in voluntary attrition in our technology roles. What is the cascading effect on project delivery and workforce cost?",
        "Write a talent supply risk report for the CHRO: the top five role families where supply is most at risk of falling short of demand in the next 24 months.",
        "Build a sourcing channel analysis: for each role family, what percentage of successful hires came from internal mobility, referrals, direct sourcing, and agencies?",
        "Identify the supply of diverse talent in our pipeline for leadership roles. Where are the greatest gaps, and at what career stage are we losing diverse talent?",
        "Model the supply impact of a hybrid or remote policy change. How does offering full remote affect our ability to access talent in new geographies?",
        "Write the assumptions our supply model makes about productivity ramp-up for new hires and transfers. How does ramp time affect our effective supply?",
        "Identify which of our talent pools are shared with competitors and most at risk of rapid supply deterioration in a hot labour market.",
        "Build a contractor-to-employee conversion model: for our most-used contractor roles, what are the cost, speed, and quality tradeoffs of converting to FTE?",
        "Write a supply model refresh protocol: what data inputs are updated monthly, quarterly, and annually, and who is responsible for each?"
      ]},
      { id:"scenario", title:"Scenario Planning", prompts:[
        "Define three workforce scenarios for our planning cycle — base case, optimistic, and stress case. For each, specify the key assumptions.",
        "Write a scenario planning facilitation guide for a three-hour workshop with senior HR and business leaders.",
        "Build a scenario matrix: on one axis, pace of technology adoption (slow vs fast); on the other, availability of skilled talent (tight vs abundant). What are the workforce implications of each quadrant?",
        "Identify the three external wild-card events that could most disrupt our workforce plan. For each, describe the trigger signal and contingency response.",
        "Write the workforce implications of an acquisition scenario: if we acquired a company of 500–1,000 employees in our core business, what integration planning is required in the first 90 days?",
        "Build a scenario where AI automates 30% of tasks in our top five role families over three years. What are the headcount, skill, and cost implications?",
        "Draft the workforce response playbook for a recession scenario: hiring freeze, attrition management, targeted reductions, and capability protection decisions in sequence.",
        "Identify the assumptions in our base-case scenario that are most sensitive to error. If we are wrong about any one of them, which has the biggest knock-on effect?",
        "Write a scenario planning narrative for the board: the three futures we are planning for, what we would do differently in each, and the decision triggers for each pivot.",
        "Model a talent market inflection: if the labour market tightens by 15% in our core engineering roles, what are the cost and timeline impacts on our hiring plan?",
        "Build a scenario for workforce transformation at scale: if we need to reskill 40% of our workforce over four years, what are the infrastructure, investment, and attrition implications?",
        "Write the assumptions audit for our workforce scenarios: for each scenario, list the five most critical assumptions, their basis, and their confidence interval.",
        "Identify leading indicators we will monitor to determine which scenario is materialising. What are the early signals, thresholds, and decision triggers?",
        "Draft a scenario for a major organisational redesign: if we move from a functional to a business unit structure, what are the workforce transition implications?",
        "Build a geopolitical risk scenario: if a key offshore delivery location becomes unavailable in 12 months, what is our workforce continuity plan?",
        "Write a scenario planning debrief framework: after a plan cycle, how do we evaluate which scenarios were most accurate and improve our future forecasting?",
        "Identify the workforce scenarios that require board-level decision authority vs those that can be managed at CHRO or business unit level.",
        "Build a real-options model for our workforce plan: which investments should we make now, which should we stage, and which should we defer?"
      ]},
      { id:"gap", title:"Gap Analysis", prompts:[
        "Build a workforce gap analysis for our top 20 critical role families: show current headcount, forecasted demand, projected supply, and net gap or surplus by year.",
        "Prioritise our workforce gaps by strategic impact: which gaps, if unfilled, most directly threaten execution of the business strategy?",
        "Write the logic for a gap severity score combining gap size, time-to-fill, cost-to-fill, and strategic criticality into a single prioritisation metric.",
        "Identify the gaps that can be closed through internal development vs those that require external hiring. What is the split and what are the cost implications?",
        "Build a capability gap map: beyond headcount, where do we have skills gaps that cannot be solved by hiring alone?",
        "Write a gap analysis one-pager for each business unit: current talent position, where they are heading, the gap, and the recommended action.",
        "Identify surplus positions in our workforce plan. How do we manage planned surpluses through attrition, redeployment, or restructuring rather than layoffs?",
        "Model the cost of our talent gaps: unfilled roles × productivity cost + overtime + contractor backfill. Quantify the business risk of inaction.",
        "Build a gap closure options analysis: for our top three critical gaps, evaluate Build (develop internally), Buy (hire externally), Borrow (contingent or partner), and Bot (automate).",
        "Write a gap analysis narrative for the CFO: what we need, what we have, the funding required to close the gap, and the cost of not closing it.",
        "Identify the gaps in our leadership pipeline: for each critical senior role, how many ready-now successors do we have? What is the average readiness deficit?",
        "Map our capability gaps against market availability of that talent. Which gaps are hard to close because the skills are scarce externally as well as internally?",
        "Build a gap analysis sensitivity table: how does our talent gap change if attrition is five points higher than forecast? Ten points higher?",
        "Write the intake questions for a gap validation workshop with business unit leaders: how do we pressure-test model outputs with people who know their businesses best?",
        "Identify gaps that are structural — will persist for three or more years — vs transient — will self-correct within 12 months. Different strategies are needed for each.",
        "Build an action registry from the gap analysis: for each prioritised gap, document the owner, strategy, target close date, and leading indicator of progress.",
        "Write a gap analysis refresh protocol: when do we update the gap map, who reviews it, and what threshold triggers a change in strategy?",
        "Draft the executive summary of our annual workforce gap analysis: the three biggest gaps, the three biggest surpluses, and the recommended portfolio of responses."
      ]}
    ]
  },
  {
    id:"skills", title:"Skills & Capability", color:"#10b981",
    files:[
      { id:"taxonomy", title:"Skills Taxonomy", prompts:[
        "Draft the architecture for an enterprise skills taxonomy: how many levels, what naming conventions, and how do we handle adjacent or overlapping skills?",
        "Identify the top ten skills categories most critical to our business strategy. For each, list five to eight specific skills that sit underneath them.",
        "Write a skills taxonomy governance model: who owns it, how often is it reviewed, how are new skills added or deprecated, and how are disputes resolved?",
        "Map our existing job architecture to a skills framework: for each job family, identify the five to seven skills that are most differentiating.",
        "Evaluate three approaches to building our skills taxonomy — bottom-up from job descriptions, top-down from strategy, market-in from a commercial ontology — and compare the tradeoffs.",
        "Write the validation protocol for our skills taxonomy: how do we test whether the skills identified are predictive of performance in each role?",
        "Identify which skills in our taxonomy are rapidly growing in market demand. These are the appreciating assets we should invest in developing now.",
        "Build a skills deprecation process: how do we identify skills becoming obsolete, how quickly, and how do we communicate this to affected employees?",
        "Write the prompt template for using AI to extract skills from job descriptions at scale. What instructions produce the most consistent output?",
        "Assess the gap between the skills in our current job descriptions and the skills actually required to perform the job today. How large is the drift?",
        "Map our skills taxonomy to external frameworks such as O*NET, ESCO, or INCOSE SECF. Where do we align, and where do we need proprietary additions?",
        "Write a skills confidence scoring model: how do we rate whether an employee has a skill, knows about it, or can lead others in it?",
        "Identify the skills critical for our business that exist nowhere in our current job architecture — the hidden skills management relies on but does not formally recognise.",
        "Build a skills adjacency map for our top five critical skills: what related skills does someone already need to develop each one efficiently?",
        "Draft the employee communication for rolling out skills profiles: why we are doing this, what we will do with the data, and how it benefits them.",
        "Write a skills taxonomy ROI model: what business decisions will be better because we have a skills taxonomy? Quantify the value of three use cases.",
        "Identify the data sources we will use to keep our skills taxonomy current: job market data, internal performance data, L&D completion rates, manager assessments.",
        "Build a skills taxonomy implementation roadmap: pilot with one function, validate, then scale. What are the milestones, risks, and success criteria?"
      ]},
      { id:"capability", title:"Capability Assessment", prompts:[
        "Design a capability assessment framework for our organisation: what are the 8–12 core capability areas we will assess, and how does this connect to our strategy?",
        "Write the survey items for a manager capability assessment. Cover technical depth, team development, execution rigour, and strategic thinking. Five items per domain.",
        "Build a capability heat map template: rows are role families, columns are capability areas, cells show current proficiency vs required proficiency.",
        "Identify the three capabilities where we have the largest gap between current and required levels. What is the root cause in each case?",
        "Write an assessment calibration guide for managers: how do we reduce rater bias and ensure consistent capability ratings across teams and functions?",
        "Design a 360-degree capability assessment for senior leaders: what sources and what capability dimensions?",
        "Build a capability assessment scoring rubric: define Level 1 (developing), Level 2 (proficient), Level 3 (advanced), and Level 4 (expert) behaviourally for our top three critical capabilities.",
        "Identify the capabilities most difficult to assess accurately through self-report. What supplementary assessment methods give more reliable data?",
        "Write the debrief guide for sharing capability assessment results with employees: how do we make it developmental rather than evaluative?",
        "Map capability assessment results to workforce planning outputs: how does the capability heat map inform our build vs buy vs borrow decisions?",
        "Design a team-level capability assessment: how do we aggregate individual data to produce an accurate view of team-level strength and risk?",
        "Build a capability assessment cadence: how often, for which populations, and how do we track progress without assessment fatigue?",
        "Identify the capabilities most predictive of high performance in our most critical roles. These should get the most weight in our assessment and development investments.",
        "Write a capability assessment validation study design: how do we test whether our capability ratings predict the outcomes we care about?",
        "Design a leadership capability assessment for our succession pipeline. What is the minimum capability bar for each executive role?",
        "Build a capability gap prioritisation matrix combining gap size, strategic importance, and time sensitivity. Use this to sequence capability investments.",
        "Write the capability assessment report for the CHRO: current capability profile, where we need to be in three years, the gap, and the investment required.",
        "Design an ongoing capability sensing mechanism: how do we monitor capability levels between formal assessment cycles?"
      ]},
      { id:"reskilling", title:"Reskilling Roadmap", prompts:[
        "Build a reskilling needs analysis: identify which employee populations need to reskill, in what skills, and on what timeline based on our workforce plan.",
        "Write the business case for a reskilling investment: projected cost of building vs buying talent, reduced attrition benefit, and productivity ramp comparison.",
        "Map our existing L&D programmes to the capability gaps in our workforce plan. Identify programmes addressing real gaps vs legacy investments.",
        "Build a reskilling pathway for our most at-risk employee population: step-by-step from current skills to target skills, with timeline, format, and cost for each step.",
        "Write a reskilling build-vs-buy analysis: for our top three critical skill gaps, is it faster and cheaper to reskill existing employees or hire people who already have the skills?",
        "Identify the employees most likely to successfully reskill based on prior learning agility, adjacent skills, and career stage.",
        "Design the reskilling programme for a specific role-to-role transition. What are the required learning milestones and the realistic timeline?",
        "Write the change management plan for a reskilling initiative affecting 20% or more of a workforce. How do we build motivation, manage anxiety, and sustain momentum?",
        "Build a reskilling ROI measurement framework: what metrics do we track before, during, and after the programme to evaluate whether it is working?",
        "Identify which skills can realistically be developed through formal training vs on-the-job experience vs stretch assignments. Sequence the reskilling pathway accordingly.",
        "Write the manager enablement plan for supporting reskilling in your team: what do managers need to know, do differently, and stop doing?",
        "Design a reskilling cohort model: how do we create peer learning groups, accountability structures, and shared milestones to improve completion rates?",
        "Identify the structural barriers to reskilling — time (workload), incentive (pay linked to current role), access (programme availability) — and write a mitigation plan for each.",
        "Build a reskilling vendor selection rubric: what criteria do we use to evaluate L&D providers, online platforms, and bootcamp partners?",
        "Write the employee value proposition for our reskilling programme: why should an employee invest time in this, and what will they get in return?",
        "Design an apprenticeship or cohort-based learning model for critical roles where formal training alone is insufficient.",
        "Map the reskilling roadmap to the workforce plan: which reskilling investments need to be completed by quarter to keep pace with the demand forecast?",
        "Write a reskilling risk register: what are the top risks to programme success — engagement, manager resistance, content quality, speed — and the mitigation for each?"
      ]},
      { id:"critical-roles", title:"Critical Roles", prompts:[
        "Design a critical role identification methodology: what criteria — strategic impact, replaceability, skill scarcity, value creation — determine whether a role is critical? Weight each criterion.",
        "Map our current critical roles against succession depth: for each, how many ready-now, one-year, and two-year successors do we have? Where are the single points of failure?",
        "Write the business case for investing in succession planning for our top 20 critical roles: what is the cost of an unplanned vacancy, and what would a strong bench be worth?",
        "Identify the critical roles at highest attrition risk in the next 12 months. Combine flight risk indicators with role criticality to build a prioritised risk register.",
        "Build a critical role profile template capturing key accountabilities, required experiences, success factors, and time to productivity.",
        "Design the assessment process for evaluating successor readiness. What combination of track record, capability assessment, and development need gives the most accurate picture?",
        "Write a succession acceleration plan for a specific critical role: identify the gap between a named successor and readiness, and design the 18-month development plan.",
        "Identify the critical roles most exposed to external talent poaching. What retention strategies are most effective for each role type?",
        "Build an emergency succession protocol: if a top-three critical role became vacant today, what is the decision process for interim assignment and permanent succession?",
        "Write the governance model for succession planning: who nominates successors, who assesses readiness, who approves decisions, and how often is the plan reviewed?",
        "Identify critical roles likely to change significantly in scope over the next three years due to technology or strategy shifts.",
        "Design the development assignment portfolio for high-potential successors: what mix of stretch assignments, cross-functional moves, and external exposure develops the broadest experience base?",
        "Write the metrics dashboard for succession health: successor coverage ratio, readiness scores, diversity of successor pool, and vacancy fill time.",
        "Build a critical role network map: which critical roles are most interdependent, and how does a vacancy in one cascade into risk in others?",
        "Write a succession planning communication strategy: how do we tell high-potentials they are in the pipeline, what do we promise them, and how do we retain them?",
        "Design the annual talent review process for critical roles: who attends, what data is reviewed, what decisions are made, and what follow-through accountability exists?"
      ]}
    ]
  },
  {
    id:"orgdesign", title:"Org Design", color:"#f59e0b",
    files:[
      { id:"structure", title:"Structural Alternatives", prompts:[
        "Map our current organisational structure and identify the three design tensions most limiting performance: speed of decision, coordination cost, or role clarity.",
        "Generate three alternative org design options for a function or business unit — functional, business unit, and matrix. For each, list the performance benefits, coordination costs, and implementation risks.",
        "Write the design criteria for our org redesign: what does the new structure need to optimise for, and what are the explicit tradeoffs we are willing to make?",
        "Build a decision rights analysis for our current structure: where are decisions made too high (bottlenecks), too low (risk), or in the wrong function (friction)?",
        "Identify the top five coordination failure points in our current structure. For each, diagnose whether it is a structural problem or a process and culture problem.",
        "Write a pros-and-cons analysis of moving from a functional to a business unit structure. Include speed, cost, talent development, and cultural implications.",
        "Design the interface model between two functions with high friction: what decisions need to be made jointly, who has final call, and what escalation path clears deadlock?",
        "Build a structural alignment check: does our current org structure optimally support our primary value creation model — cost, speed, innovation, or relationship?",
        "Write the criteria for deciding when a matrix structure is appropriate vs when it creates more complexity than it solves.",
        "Map the informal organisation: who are the central connectors, the brokers between silos, and the isolated nodes? How does this differ from the formal chart?",
        "Design a team-of-teams model for an initiative that cuts across three or more functions. Who owns what, how do they coordinate, and how do we prevent re-centralisation?",
        "Identify which parts of our organisation are over-structured — too many layers, too many committees — and which are under-structured — unclear accountability, informal workarounds.",
        "Write a redesign impact assessment: if we implement the preferred option, what roles are eliminated, what roles are created, what roles change significantly?",
        "Build an org design evaluation scorecard: rate each structural option on strategic alignment, operating efficiency, talent development, customer focus, and change cost.",
        "Write the change narrative for a proposed redesign: why now, what is changing, what is not changing, and what will be better for employees and customers?",
        "Design the transition state: what interim structure do we use between current and future state, and how long does the transition period last?",
        "Identify the key risks of a decentralised structure — talent fragmentation, inconsistent practices, scale loss — and write the mitigation plan.",
        "Write a stakeholder analysis for an org redesign: who wins, who loses, who is uncertain, and how do we manage each group through the process?"
      ]},
      { id:"spans-layers", title:"Spans & Layers", prompts:[
        "Analyse our current span of control by function and level. Where are we below the target minimum of four direct reports and above the target maximum of twelve?",
        "Benchmark our spans and layers against industry norms for an organisation of our size and complexity. Where are we materially different, and is that intentional?",
        "Identify the cost of excess layers in our organisation: how many management roles exist primarily to supervise rather than add value? What is the fully-loaded cost?",
        "Write the criteria for an appropriate span of control: what factors — work complexity, geographic dispersion, employee tenure, task interdependence — justify a narrower span?",
        "Build a spans and layers optimisation model: if we move to a target number of layers and average span, what is the impact on headcount, cost, and decision speed?",
        "Identify the functions or teams where narrow spans of control are creating slow decision-making and excessive escalation. What is the recommended redesign?",
        "Write a manager effectiveness analysis: do managers with wider spans have better or worse team outcomes in our data? What does this tell us?",
        "Design the role of the middle manager in a leaner, flatter structure. What does the job need to look like for the new span to be manageable?",
        "Identify the organisational symptoms of too many layers: slow decisions, distorted information, manager disengagement. Where do we see these signals?",
        "Write the communication strategy for a spans and layers redesign that reduces management headcount.",
        "Build a role elimination and consolidation plan: for managers with fewer than three direct reports, what are the options — consolidate, convert to IC, eliminate?",
        "Design the governance for spans and layers standards: how do we prevent layer creep over time, who owns the standard, and what triggers a review?",
        "Identify the relationship between spans and layers and our engagement scores: are employees in over-managed teams less engaged?",
        "Write a spans and layers change management plan: how do we help managers transition from managing a narrow team to managing a wider, more empowered one?",
        "Build the metrics we will track post-redesign to evaluate whether the new spans and layers structure is performing as intended.",
        "Write the senior leader talking points for explaining why the organisation needs fewer layers: the employee benefit, the business benefit, and the commitment to people whose roles change."
      ]},
      { id:"role-clarity", title:"Role Clarity", prompts:[
        "Audit our job architecture for the top 20 most common roles: do each have clear, differentiated accountabilities at each level, or is there significant overlap?",
        "Write a RACI matrix for our top three cross-functional processes. Identify every step where there are two or more R's — indicating unclear ownership — or no R.",
        "Design a role profile template for critical roles capturing key decisions owned, stakeholders managed, and success criteria.",
        "Identify the top three recurring accountability disputes in our organisation. For each, diagnose whether the root cause is structural or behavioural.",
        "Write a job levelling framework for our engineering function: what are the differentiating criteria between levels?",
        "Build a decision authority matrix for a function: what decisions can be made at each level without approval, which require one level up, and which require executive sign-off?",
        "Identify roles that have expanded significantly beyond their original scope without being formally reclassified. What are the equity and retention risks?",
        "Write the process for resolving a role conflict between two teams that both claim ownership of a key deliverable.",
        "Design a role clarity workshop for a team experiencing high friction: what exercises surface hidden assumptions about who owns what?",
        "Build a job architecture review cadence: how often do we audit role profiles, who participates, and what triggers an off-cycle review?",
        "Identify the roles most at risk of scope creep. What structural or governance interventions prevent the problem rather than just diagnosing it?",
        "Write the role transition plan for a significant scope expansion: how do we set new expectations, provide support, and adjust compensation?",
        "Design the process for creating a new role: what approvals are required, what analysis is needed, and how is it integrated into job architecture?",
        "Identify the accountability gaps created by our recent org redesign: which activities previously owned by eliminated roles are now unowned?",
        "Write a role clarity assessment survey for teams: five to eight questions that quickly surface ambiguity about ownership, decision rights, and success criteria.",
        "Build the governance model for our job architecture: who owns it, who can modify it, and how do we prevent divergence between the formal architecture and actual practice?",
        "Identify the impact of role ambiguity on engagement scores in our data. Use this as a business case for investing in role clarity.",
        "Write the job architecture change communication: when we update levels, titles, or role profiles, how do we explain the change and minimise anxiety?"
      ]},
      { id:"effectiveness", title:"Effectiveness Measurement", prompts:[
        "Design an org effectiveness measurement framework: what are the five to eight dimensions we will assess — agility, alignment, execution, culture, innovation?",
        "Build an org health diagnostic survey: 15–20 items that give a reliable snapshot of team-level health across our priority dimensions.",
        "Identify the leading vs lagging indicators of organisational effectiveness. Which metrics predict problems early enough to intervene?",
        "Write a team performance measurement model: how do we assess whether a team is achieving its intended outputs, using its resources efficiently, and building capability?",
        "Design a network analysis approach to measure informal collaboration patterns. What does the data tell us about information flow, silos, and key connectors?",
        "Build an effectiveness metric dashboard for a business unit leader: the five to seven people and organisation health metrics that most predict business outcomes.",
        "Identify the organisational behaviours most associated with high performance. How do we measure whether those behaviours are present at scale?",
        "Write the measurement framework for evaluating the success of an org redesign: what do we measure before, during, and after the transition?",
        "Design a manager effectiveness index: what combination of team outcomes — engagement, attrition, performance distribution, internal mobility — gives the most reliable signal?",
        "Build a collaboration effectiveness measure: for cross-functional teams, how do we assess whether they are working well together vs experiencing structural friction?",
        "Identify the measurement gaps in our current org effectiveness toolkit. What are we not measuring that we should be?",
        "Write the governance for our org effectiveness measurement programme: how often do we measure, who sees the results, and what decision rights follow from the data?",
        "Design an early warning system for organisational dysfunction: what signals — attrition clustering, engagement outliers, escalation frequency — indicate a team is at risk?",
        "Build a benchmark database for our org health metrics: how do we compare our scores to industry norms and our own historical trend?",
        "Write the debrief process for org effectiveness results: how do leaders receive feedback, what is the action planning process, and how do we follow up?",
        "Identify the relationship between our org health scores and business unit performance outcomes. Where is the correlation strongest?"
      ]}
    ]
  },
  {
    id:"transformation", title:"Transformation", color:"#3b82f6",
    files:[
      { id:"change", title:"Change Strategy", prompts:[
        "Build a change impact assessment for our transformation initiative: which employee populations are affected, how significantly, and in what dimensions?",
        "Write a change readiness assessment: 10–12 survey items measuring employee readiness across awareness, understanding, acceptance, and capability dimensions.",
        "Design a change management strategy for a transformation affecting 50% or more of the workforce. What are the key phases, milestones, and critical path?",
        "Identify the top five change risks in our transformation initiative. For each, assess probability and impact, and write a mitigation plan.",
        "Write the change narrative: why are we transforming, what will be different, what will stay the same, and what is the benefit for employees?",
        "Build a resistance management plan: who are the most likely resisters, what are their concerns, and how do we engage them before they become blockers?",
        "Design the leader activation plan: what do senior leaders need to do differently to model the change?",
        "Write a change agent network design: how many change champions do we need, how do we select them, and what do we ask them to do?",
        "Identify the cultural barriers to our transformation. Which existing norms and behaviours are most at odds with what the new operating model requires?",
        "Build a change measurement model: how do we track adoption, behaviour change, and outcome realisation at each phase of the transformation?",
        "Write the manager activation guide for the transformation: what do managers need to know, communicate, and do differently?",
        "Design an employee listening strategy for the transformation: what channels, what cadence, and how do we close the loop on what we hear?",
        "Identify the quick wins in the transformation that will build credibility and momentum. What visible changes can we deliver in the first 90 days?",
        "Write the escalation protocol for the transformation: what issues get escalated to the steering committee, what gets handled at programme level?",
        "Build a change saturation analysis: how many other major changes are employees absorbing simultaneously? Where is the overload risk highest?",
        "Design the transition support package for employees most significantly impacted: career counselling, reskilling support, and transition time.",
        "Write the post-transformation sustainment plan: what governance, reinforcement, and measurement ensures the change sticks?",
        "Identify the behavioural signals that indicate the transformation is working vs stalling. What does healthy adoption look like at 30, 60, and 90 days?",
        "Write the lessons learned framework for our transformation: what did we plan for that we did not need, what caught us off guard?",
        "Design the transformation governance model: who is on the steering committee, what decisions do they own, and how does programme management connect to the business?"
      ]},
      { id:"stakeholder", title:"Stakeholder Mapping", prompts:[
        "Build a stakeholder map for our transformation: identify every key stakeholder group, their level of interest, level of influence, and current stance.",
        "Write a stakeholder engagement strategy for each quadrant of our influence-interest matrix.",
        "Identify the three stakeholders whose resistance could most derail our transformation. Write a targeted engagement plan for each.",
        "Design a coalition-building strategy: which stakeholders, if aligned, would give us enough momentum to move the transformation forward without universal buy-in?",
        "Write the executive sponsor brief: what does our most senior sponsor need to do, say, and model at each phase of the transformation?",
        "Build a stakeholder sentiment tracker: how do we monitor stakeholder stance over time?",
        "Identify the informal influencers in our organisation who are not on the org chart but significantly shape opinion. How do we engage them?",
        "Write stakeholder-specific messages: the CHRO message, business unit leader message, front-line manager message, and employee message.",
        "Design the stakeholder engagement rhythm: who do we meet with, how often, and for what purpose at each phase?",
        "Build a power-interest grid and identify the fence-sitters — high-influence stakeholders who are currently undecided. What is our strategy for each?",
        "Write the briefing document for a sceptical CFO on our transformation ROI: here is the investment, here is the return, here is the risk-adjusted case.",
        "Identify the stakeholder groups most likely to experience loss in the transformation. How do we acknowledge and manage that loss?",
        "Design a board-level engagement strategy for the transformation: what do we communicate, when, and how do we build board confidence?",
        "Write the cross-functional alignment session agenda for the leaders of the three functions most impacted by the transformation.",
        "Build a stakeholder accountability matrix: for each key stakeholder commitment, who made it, what specifically did they commit to, and how do we track follow-through?",
        "Identify external stakeholders — union, regulators, customers, investors — who have a stake in our workforce transformation.",
        "Write the burning platform narrative for stakeholders who believe the status quo is acceptable.",
        "Design the post-transformation stakeholder feedback loop: how do we learn from key stakeholders whether the change delivered what we promised?"
      ]},
      { id:"comms", title:"Communications", prompts:[
        "Write a transformation communication strategy: communication objectives, audiences, key messages, channels, and cadence for each phase.",
        "Build a message architecture for our transformation: the anchor message, supporting messages by audience, and the proof points that make each message credible.",
        "Write the all-employee announcement for our transformation: clear, honest, and focused on what employees most need to know first.",
        "Design the communication cadence for the transformation: what do we communicate at launch, at 30 days, at each major milestone, and at go-live?",
        "Write the manager Q&A guide: the ten questions employees are most likely to ask, with model answers for each.",
        "Build a channel strategy: which messages go through email, town hall, team meeting, intranet, video, or one-on-one?",
        "Write the what's-in-it-for-me message for each major employee population.",
        "Design a two-way communication mechanism: how do employees share concerns, ask questions, and give feedback?",
        "Write the crisis communication template for when something goes wrong in the transformation.",
        "Build a rumour management protocol: when misinformation spreads, what is the process for identifying it, correcting it, and rebuilding trust?",
        "Write the communication for a difficult transformation message — role eliminations, location closures, significant scope changes.",
        "Design the leader communication toolkit: pre-written talking points, FAQ documents, and presentation templates.",
        "Write the six-month transformation update communication: what progress do we report, how do we acknowledge what is harder than expected?",
        "Build a communication measurement framework: how do we assess message reach, comprehension, and behavioural impact?",
        "Write the change story for an external audience — customers, partners, investors: how do we frame our workforce transformation as a positive signal?",
        "Design the communication wind-down for the end of the formal transformation programme.",
        "Identify the communication mistakes most common in large-scale transformations. Which are we most at risk of making?",
        "Write the communication debrief guide for post-transformation review: what questions do we ask about what worked and what we would do differently?"
      ]},
      { id:"measurement", title:"Measurement Framework", prompts:[
        "Build a workforce transformation measurement framework: define outcomes at three levels — activity, behaviour change, business impact — and identify a metric and data source for each.",
        "Write the business case for our transformation investment: expected ROI, over what timeframe, and how do we isolate the workforce intervention's contribution?",
        "Design the baseline measurement protocol: what do we measure before the transformation begins to enable meaningful before-and-after comparison?",
        "Build a leading indicator dashboard for our transformation: what metrics tell us the transformation is on track six to twelve months before we see business results?",
        "Write the attribution methodology for our workforce analytics programme: how do we claim credit for outcomes that have multiple contributing causes?",
        "Design a workforce ROI model for the CHRO: for each major people investment, what is the expected financial return and how is it calculated?",
        "Build a maturity model for our workforce intelligence function: what does Level 1 through Level 5 look like across strategy, analytics, technology, talent, and governance?",
        "Write the measurement framework for our reskilling programme: completion rates, skill acquisition rates, time-to-productivity, and reduction in external hiring.",
        "Identify the workforce metrics most directly correlated with revenue growth in our business. Use this to build a business case.",
        "Design a workforce analytics value realisation tracker: for each analytics use case in production, how do we track whether the intended decisions are being made differently?",
        "Write the annual workforce intelligence report structure: what metrics, narratives, and recommendations should every annual people analytics report contain?",
        "Build a measurement governance model: who owns which metrics, how are definitions managed, and how do we resolve disputes?",
        "Design an impact evaluation study for a specific people programme using a quasi-experimental design.",
        "Write the methodology for calculating the cost of voluntary attrition: direct costs, indirect costs, and opportunity costs.",
        "Identify the workforce metrics we are currently reporting that no one is using to make decisions. What should we stop measuring?",
        "Build a workforce strategy scorecard for the board: six to eight metrics that give board members a reliable view of workforce health and trajectory.",
        "Write the workforce analytics capability roadmap: from descriptive reporting today to predictive modelling in 18 months.",
        "Design the workforce intelligence function's annual planning process: how do we identify the questions the business most needs answered?"
      ]}
    ]
  }
];
